apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
        - name: task-service
          image: task-service:latest
          imagePullPolicy: Never
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/tasksdb"
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: yourpassword
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:29092"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: task-service
spec:
  type: LoadBalancer
  selector:
    app: task-service
  ports:
    - port: 8080
      targetPort: 8080
